name: animeguri
publish_to: 'none'

environment:
  sdk: ^3.10.4

workspace:
  - packages/app
  - packages/data
  - packages/domain
  - packages/foundation
  - packages/model
  - packages/ui

dev_dependencies:
  melos: ^7.3.0
  very_good_analysis: ^10.0.0

melos:
  command:
    bootstrap:
      hooks:
        post: |
          melos exec -c 4 --file-exists="pubspec_overrides.yaml" -- "rm pubspec_overrides.yaml"
          melos gen
        description: Runs build_runner after melos bootstrap

    clean:
      hooks:
        post: melos exec -c 4 -- "flutter clean"
        description: Runs flutter clean after melos clean

  scripts:
    get:
      run: melos exec -c 4 -- "flutter pub get" && melos gen
      description: Runs flutter pub get and melos gen

    gen:
      run: melos gen:all --no-select
      description: Runs gen:all

    gen:all:
      run: melos exec -c 4 -- "flutter pub run build_runner build --delete-conflicting-outputs"
      description: Runs build_runner build
      packageFilters:
        dependsOn: build_runner

    watch:
      run: melos gen && melos watch:all
      description: Runs watch:all

    watch:all:
      run: melos exec -c 4 -- "flutter pub run build_runner watch --delete-conflicting-outputs"
      description: Runs build_runner watch
