name: presentation
description: "Presentation layer for animeguri."

environment:
  sdk: '>=3.3.4 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  # Local packages
  foundation:
    path: ../foundation
  model:
    path: ../model

  auto_route: ^10.0.0
  flutter_hooks: ^0.21.0
  gap: ^3.0.1
  collection: ^1.18.0

dev_dependencies:
  build_runner: ^2.4.9
  auto_route_generator: ^10.0.0
  very_good_analysis: ^9.0.0

flutter:
