name: app
publish_to: 'none'

version: 0.0.1

environment:
  sdk: ^3.10.4
  flutter: ">=3.24.0"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter

  # Local packages
  data:
    path: ../data
  domain:
    path: ../domain
  foundation:
    path: ../foundation
  model:
    path: ../model
  ui:
    path: ../ui

  firebase_core: ^4.3.0
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  very_good_analysis: ^10.0.0

flutter:
  uses-material-design: true
