name: ui
description: "UI layer for animeguri."
publish_to: 'none'

environment:
  sdk: ^3.10.4
  flutter: ">=3.24.0"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter

  # Local packages
  domain:
    path: ../domain
  foundation:
    path: ../foundation

  auto_route: 11.1.0
  flutter_hooks: ^0.21.0
  flutter_riverpod: ^3.0.3
  hooks_riverpod: ^3.0.3
  riverpod: ^3.0.3
  riverpod_annotation: ^3.0.3
  freezed_annotation: ^3.0.6
  meta: ^1.17.0
  gap: ^3.0.1
  collection: ^1.18.0
  uuid: ^4.5.2
  lucide_icons: ^0.257.0

dev_dependencies:
  build_runner: ^2.4.9
  auto_route_generator: ^10.0.0
  riverpod_generator: ^3.0.3
  very_good_analysis: ^10.0.0
  freezed: ^3.0.0

flutter:
  uses-material-design: true
