name: ui
description: "UI layer for animeguri."
publish_to: 'none'

environment:
  sdk: ^3.10.4
  flutter: ">=3.24.0"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter

  # Local packages
  foundation:
    path: ../foundation
  model:
    path: ../model

  auto_route: 11.1.0
  flutter_hooks: ^0.21.0
  gap: ^3.0.1
  collection: ^1.18.0

dev_dependencies:
  build_runner: ^2.4.9
  auto_route_generator: ^10.0.0
  very_good_analysis: ^10.0.0

flutter:
  uses-material-design: true
