name: domain
description: 'Domain layer for animeguri.'
publish_to: 'none'

environment:
  sdk: ^3.10.4

resolution: workspace

dependencies:
  # Local packages
  foundation:
    path : ../foundation

  result_dart: ^2.1.1
  riverpod: ^3.0.3
  riverpod_annotation: 4.0.2
  freezed_annotation: ^3.0.6
  json_annotation: ^4.9.0

dev_dependencies:
  build_runner: ^2.4.9
  very_good_analysis: ^10.0.0
  riverpod_generator: ^3.0.3
  freezed: ^3.0.0
  json_serializable: ^6.9.5
