name: domain
description: 'Domain layer for animeguri.'
publish_to: 'none'

environment:
  sdk: ^3.10.4

resolution: workspace

dependencies:
  # Local packages
  foundation:
    path : ../foundation
  model:
    path : ../model
  ui:
    path : ../ui

dev_dependencies:
  build_runner: ^2.4.9
  very_good_analysis: ^10.0.0
